# Generated by Django 5.1.2 on 2024-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('home_team', models.IntegerField()),
                ('away_team', models.IntegerField()),
                ('home_team_goals', models.JSONField()),
                ('home_team_assists', models.JSONField()),
                ('home_team_own_goals', models.JSONField()),
                ('home_team_penalties_saved', models.JSONField()),
                ('home_team_penalties_missed', models.JSONField()),
                ('home_team_yellow_cards', models.JSONField()),
                ('home_team_red_cards', models.JSONField()),
                ('home_team_saves', models.JSONField()),
                ('away_team_goals', models.JSONField()),
                ('away_team_assists', models.JSONField()),
                ('away_team_own_goals', models.JSONField()),
                ('away_team_penalties_saved', models.JSONField()),
                ('away_team_penalties_missed', models.JSONField()),
                ('away_team_yellow_cards', models.JSONField()),
                ('away_team_red_cards', models.JSONField()),
                ('away_team_saves', models.JSONField()),
            ],
        ),
    ]
