# Generated by Django 5.1.2 on 2024-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPLUser', '0002_alter_fpluser_players_alter_fpluser_startingxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpluser',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
